name: Staging Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Railway CLI
      run: npm i -g @railway/cli

    - name: Run Database Migrations
      run: npm run db:migrate
      env:
        PGHOST: ${{ vars.PGHOST }}
        PGPORT: ${{ vars.PGPORT }}
        PGUSER: ${{ vars.PGUSER }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
        PGDATABASE: ${{ vars.PGDATABASE }}

    - name: Deploy to Railway Staging
      run: railway up --service fastify-webapp-sample -e staging
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_STAGING_TOKEN }}

  e2e-staging:
    name: E2E Tests on Staging
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      working-directory: e2e
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run E2E tests
      run: npm test
      working-directory: e2e
      env:
        BASE_URL: https://fastify-webapp-sample-staging-a8c7.up.railway.app
        HEADLESS: true

    - name: Load test rport history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_report: allure-report
        allure_results: e2e/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history

  deploy-production:
    name: Deploy to Production
    needs: e2e-staging
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Railway CLI
      run: npm i -g @railway/cli

    - name: Run Database Migrations
      run: npm run db:migrate
      env:
        PGHOST: ${{ vars.PGHOST }}
        PGPORT: ${{ vars.PGPORT }}
        PGUSER: ${{ vars.PGUSER }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
        PGDATABASE: ${{ vars.PGDATABASE }}

    - name: Deploy to Railway Production
      run: railway up --service fastify-webapp-sample -e production
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}