name: Staging Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Railway CLI
      run: npm i -g @railway/cli

    - name: Deploy to Railway Staging
      run: railway up --service fastify-webapp-sample -e staging
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_STAGING_TOKEN }}

    # GitHub環境コンテキストが理解できていないので、一旦コメントアウト
    # 現状、マイグレーションはローカルマシンから実行している
    # TODO: GitHub Actions上でDBマイグレーションするようようにする
    - name: Run Database Migrations
      run: railway run npm run db:migrate
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_STAGING_TOKEN }}
        PGHOST: ${{ vars.PGHOST }}
        PGPORT: ${{ vars.PGPORT }}
        PGUSER: ${{ vars.PGUSER }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
        PGDATABASE: ${{ vars.PGDATABASE }}

  e2e-staging:
    name: E2E Tests on Staging
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      working-directory: e2e
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run E2E tests
      run: npm test
      working-directory: e2e
      env:
        BASE_URL: https://fastify-webapp-sample-staging-a8c7.up.railway.app
        HEADLESS: true